[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]

remappings = [
    '@safe=src/safe',
    '@safe-global/safe-core-protocol=lib/safe-core-protocol', 
    '@safe-contracts=lib/safe-contracts',
    '@openzeppelin=lib/openzeppelin-contracts',
    '@foundry-devops=lib/foundry-devops',
    '@aave=lib/aave-v3-core/contracts',
    '@chainlink/contracts-ccip=lib/ccip/contracts'
    
    ]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
